#!/usr/bin/env bash
# statusline-setup installer — set up / update the Claude Code custom status line.
# Auto-detects Vibe Island:
#   present -> append render block into ~/.vibe-island/bin/vibe-island-statusline (keeps the notch)
#   absent  -> install ~/.claude/statusline.sh and register it in settings.json
# Idempotent: the render block is wrapped in markers and replaced on every re-run.
set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BODY="$SKILL_DIR/statusline-body.sh"
MARK_BEG="# >>> claude-statusline (managed by statusline-setup) >>>"
MARK_END="# <<< claude-statusline (managed by statusline-setup) <<<"
STAMP="$(date +%Y%m%d%H%M%S)"

die() { printf '\342\234\227 %s\n' "$*" >&2; exit 1; }

command -v jq >/dev/null 2>&1 || die "需要 jq。装好后重跑：  brew install jq   (Linux: sudo apt-get install -y jq)"
command -v git >/dev/null 2>&1 || printf '\302\267 \346\234\252\346\243\200\346\265\213\345\210\260 git\357\274\232\345\210\206\346\224\257\346\256\265\344\270\215\344\274\232\346\230\276\347\244\272\357\274\210\344\270\215\345\275\261\345\223\215\345\205\266\344\275\231\357\274\211\343\200\202\n'
[ -f "$BODY" ] || die "技能文件缺失：找不到 $BODY"

# strip any existing managed block (stdin -> stdout)
strip_block() {
  awk -v b="$MARK_BEG" -v e="$MARK_END" '
    $0==b {inblk=1; next}
    $0==e {inblk=0; next}
    !inblk {print}
  '
}

VI="$HOME/.vibe-island/bin/vibe-island-statusline"

if [ -f "$VI" ]; then
  MODE="vibe-island"
  cp "$VI" "$VI.bak.$STAMP"
  tmp="$(mktemp)"
  strip_block < "$VI" > "$tmp"
  {
    printf '\n%s\n' "$MARK_BEG"
    cat "$BODY"
    printf '%s\n' "$MARK_END"
  } >> "$tmp"
  cat "$tmp" > "$VI"          # write back into existing file -> keep perms/inode
  rm -f "$tmp"
  TARGET="$VI"
  printf '\342\234\223 已注入 Vibe Island 脚本（刘海/灵动岛保持工作）：%s\n' "$VI"
  printf '  备份：%s\n' "$VI.bak.$STAMP"
else
  MODE="standalone"
  mkdir -p "$HOME/.claude"
  TARGET="$HOME/.claude/statusline.sh"
  {
    printf '#!/bin/bash\n'
    printf '# Auto-generated by the statusline-setup skill. Re-run the skill to update.\n'
    printf 'input=$(cat)\n'
    printf '%s\n' "$MARK_BEG"
    cat "$BODY"
    printf '%s\n' "$MARK_END"
  } > "$TARGET"
  chmod +x "$TARGET"
  printf '\342\234\223 已写入独立脚本：%s\n' "$TARGET"

  SETTINGS="$HOME/.claude/settings.json"
  if [ ! -f "$SETTINGS" ] || ! jq -e . "$SETTINGS" >/dev/null 2>&1; then
    [ -f "$SETTINGS" ] && cp "$SETTINGS" "$SETTINGS.bak.$STAMP"
    printf '{}\n' > "$SETTINGS"
  fi
  existing="$(jq -r '.statusLine.command // empty' "$SETTINGS" 2>/dev/null)"
  if [ -n "$existing" ] && [ "$existing" != "$TARGET" ]; then
    cp "$SETTINGS" "$SETTINGS.bak.$STAMP"
    printf '\302\267 \346\263\250\346\204\217\357\274\232\345\216\237 statusLine \346\214\207\345\220\221 %s\357\274\214\345\267\262\345\244\207\344\273\275\345\271\266\346\233\277\346\215\242\343\200\202\n' "$existing"
  fi
  tmp="$(mktemp)"
  jq --arg c "$TARGET" '.statusLine={type:"command",command:$c}' "$SETTINGS" > "$tmp" && mv "$tmp" "$SETTINGS"
  printf '\342\234\223 已在 settings.json 注册 statusLine。\n'
fi

# preview with synthetic data (built from BODY, so it never touches the Vibe Island cache/settings)
now="$(date +%s)"; r5=$((now+12180)); r7=$((now+300000))
sample=$(printf '{"model":{"display_name":"Opus 4.8"},"context_window":{"used_percentage":42},"rate_limits":{"five_hour":{"used_percentage":47,"resets_at":%s},"seven_day":{"used_percentage":80,"resets_at":%s}}}' "$r5" "$r7")
pv="$(mktemp)"
{ printf '#!/bin/bash\ninput=$(cat)\n'; cat "$BODY"; } > "$pv"
printf '\n—— 预览（合成数据）——\n'
printf '%s' "$sample" | bash "$pv"
rm -f "$pv"
printf '\n\n模式：%s  ·  重开 Claude Code 或发一条消息即生效。\n' "$MODE"
